### ISSUE TITLE
Add meta Data to NgxFileUploadOptions

### ISSUE THREAD

**Issue by Ambitiont109** [r-hannuschka/ngx-fileupload#365]
Hello
I need a new feature that can add some information to FormData like below
.
this.uploadOptions = {
      url: `${environment.API_URL}/child/${this.childId}/upload_picture/`,
      formData: {
        enabled:true,
        name:'image',
        meta:{
                       'fileName' : '',
                       'role': 'schoolDocument.'
                 }
      }
    };

if you entrust it to me, I can do it in one day.

**Comment by r-hannuschka** [comment]
Hey, sry for super late response.

Yeah for sure i trust you the problem ist this repository is currently not well maintained from my side (to many other projects). We also face the problem it seems it is currently not angular 9 (Ivy ready).

If you want to do that feel free i'm happy about every one who wants to help.

**Comment by r-hannuschka** [comment]
Should be now possible, just pass a configuration like that:

```ts
    private uploadOptions: NgxFileUploadOptions = {
        url: "http://localhost:3000/upload/gallery",
        formData: {
            enabled: true,
            name: "picture",
            metaData: {
                role: 'DEV_NULL',
                parent: -1
            }
        },
    };
```

Request

![image](https://user-images.githubusercontent.com/25415574/120893969-32469a00-c616-11eb-8886-81d4af9fb8ce.png)

Server i got something like that:

```json
{
  ...
  files: {
    picture: {
      name: 'lunar-space-galaxy (1).jpg',
      data: <Buffer ff d8 ff e0 00 10 4a 46 49 46 00 01 01 00 00 01 00 01 00 00 ff fe 00 3b 43 52 45 41 54 4f 52 3a 20 67 64 2d 6a 70 65 67 20 76 31 2e 30 20 28 75 73 69 ... 147975 more bytes>,
      size: 148025,
      encoding: '7bit',
      tempFilePath: '',
      truncated: false,
      mimetype: 'image/jpeg',
      md5: '91b118f177b83c2109b9099541024c67',
      mv: [Function: mv]
    }
  },
  body: { metaData: '{"role":"DEV_NULL","parent":-1}' },
  route: Route {
    path: '/upload/gallery',
    stack: [ [Layer] ],
    methods: { post: true }
  }
}
```

Not sure this is everywhere the same, i just use a very simple express server with express-fileupload so for me the data is inside of body.

**Comment by Ambitiont109** [comment]
Thank you for your update.
I didn't see the message you were going to assign this task to me.
Thank you again.

**Comment by r-hannuschka** [comment]
All fine :D i did not assigned you i should ? But as there was nothing happens (okay from my side too ;) ), i implemented this now should be live now.

Next time i will assign you, since i'm happy for everyone who wants to join.

**Comment by Ambitiont109** [comment]
Okay. Thank  you.
