### ISSUE TITLE
Angular CLI 12 - build fails with default settings (strictNullChecks)

### ISSUE THREAD

**Issue by psupina** [r-hannuschka/ngx-fileupload#406]
**Describe the bug**
When I build a new Angular CLI application importing NgxFileUploadCoreModule, build fails with error:

```
Error: node_modules/@ngx-file-upload/core/lib/api/src/upload.d.ts:91:5 - error TS2411: Property 'authorization' of type 'string | AuthorizationHeader | undefined' is not assignable to string index type 'string | AuthorizationHeader'.

91     authorization?: string | AuthorizationHeader;
       ~~~~~~~~~~~~~
```

**To Reproduce**
1. Create a new Angular CLI 12 application
`ng new testfileupload`
`cd testfileupload`
2. Install @ngx-file-upload/core package
`npm i --save @ngx-file-upload/core`
3. Import NgxFileUploadCoreModule in the AppModule file:
```typescript
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { NgxFileUploadCoreModule } from '@ngx-file-upload/core';  // <-- added line

import { AppComponent } from './app.component';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    NgxFileUploadCoreModule,  // <-- added line
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }

```
4. Build the application
`ng build`

5. See these errors:
```
Error: node_modules/@ngx-file-upload/core/lib/api/src/upload.d.ts:91:5 - error TS2411: Property 'authorization' of type 'string | AuthorizationHeader | undefined' is not assignable to string index type 'string | AuthorizationHeader'.

91     authorization?: string | AuthorizationHeader;
       ~~~~~~~~~~~~~
```

**Expected behavior**
Build should succeed.

**Desktop (please complete the following information):**
 - OS: Windows 10 (20H2)
 - Angular CLI: 12.0.3
 - Node: 14.16.0
 - Package Manager: npm 6.14.11
 - @ngx-file-upload/core: 3.0.0

**Additional context**
Build fails because the default settings for Angular 12 CLI application include this flag in the "tsconfig.json" file:
```json
{
  "compilerOptions": {
    "strict": true,
  }
}
```

The "strict" option enables several flags at once. The specific flag which fails the build is "strictNullChecks".
[https://www.typescriptlang.org/tsconfig#strictNullChecks](https://www.typescriptlang.org/tsconfig#strictNullChecks)

The TS2411 error points to the "authorization" property in the NgxFileUploadHeaders interface:
[https://github.com/r-hannuschka/ngx-fileupload/blob/v3.0.0/src/projects/core/src/lib/api/src/upload.ts#L130](https://github.com/r-hannuschka/ngx-fileupload/blob/v3.0.0/src/projects/core/src/lib/api/src/upload.ts#L130)

**Comment by r-hannuschka** [comment]
Thx for issue i check this out now, sty for closing other issue maybe i need a better environment to get the same issue.

**Comment by r-hannuschka** [comment]
okay fixed "all" errors so all errors in library but the whole project even unit tests are broken with strict: true ... but valid.

I just do the same all day and fight vs eslint and now this :D But very good issue thx for point this out, a little bit angry about angular since upgrade just tells me yes yes all fine. But if you create a new project there is strict true.

**Comment by r-hannuschka** [comment]
Since i updated UI, Example and Unit tests to. Testing it in another project i think this can be closed now :)
