### ISSUE TITLE
[Question] How to send Custom fields with the file? 

### ISSUE THREAD

**Issue by JatinChimote** [r-hannuschka/ngx-fileupload#707]
**Is your feature request related to a problem? Please describe.**

How to send custom key value pairs along with file data. The current implementation considers a field 'metadata' in the UploadOption. I want to upload to S3 using a presigned url and I cannot send some custom keys like "policy", "signature" as there's simply no way to send direct formData fields. or Perhaps I am missing something.

**Describe the solution you'd like**
there should be an option to pass any key value pair to the API that takes care of the uploads, not sure what metadata is the only field.

**Describe alternatives you've considered**
Tried passing data directly but it gets stripped off in the request.

**Additional context**
So I can :
![image](https://user-images.githubusercontent.com/2509409/175068316-bcbf3396-aa43-40dc-b5c5-49d2b49058e3.png)
I want to : 
![image](https://user-images.githubusercontent.com/2509409/175069977-272974f5-59d7-40d3-9623-2b5a44dd46a5.png)

**Comment by r-hannuschka** [comment]
Let me take a look onto this one, you want to add additional form data if i see this correctly and yes it seems currently not possible.

Should be not that hard if i see this correctly :) Maybe today after work or tomorrow but this week. Alternate you can open a pull request on this i think the best way is to add this here:

https://github.com/r-hannuschka/ngx-fileupload/blob/996d23a84152a3aa7b5abb50151fb74bc1ae454d/src/projects/core/src/lib/upload/src/upload.request.ts#L216

and update the options interface.

**Comment by JatinChimote** [comment]
Awesome! Thank you so much for your quick changes and response!

**Comment by r-hannuschka** [comment]
Thx alot just let me know if this is not working for you, i tested this only with unit tests :( need to add playwright finally for better coverage so i do not need to watch server logs anymore.
