### ISSUE TITLE
Support for angular 15 & 16

### ISSUE THREAD

**Issue by Austinb** [r-hannuschka/ngx-fileupload#789]
**Describe the bug**
When trying to upgrade a current angular project to 15 there are compatibility notices for core and ui with 

**To Reproduce**
1. Update npm dependencies for an angular project (i.e. `npm update webpack`)
2. During update an error will be shown saying `@ngx-file-upload/core` could not resolve dependency `@angular/common@"^14.0.0"`

**Expected behavior**
The npm module installs without errors

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.2
 - Browser N/A
 - Version N/A

**Additional context**
Dependencies for this project need to be updated to support angular 14 and 15.  You can still install the modules using --force.

**Comment by r-hannuschka** [comment]
Sry for late Response, i will do this asap:

Angular 15
Angular 16 

this will become 2 Versions then

**Comment by Austinb** [comment]
Thank you. I would assume you could do one release version that supports both 15 and 16 using the or `|` version syntax.  This is assuming there are not issues preventing a version working on angular 15 from working on 16 other than changing the dependencies. 

Just as an aside to allow you to keep using the older version you can override the versions in your `package.json` file so you do not have to use `--force` or something similar when installing. If you are using 16 just change the versions to `16`. Obviously supported versions are better but we had to do something to remove the `--force` flag from our stack.

```
"overrides": {
    "@ngx-file-upload/core": {
      "@angular/common": "^15.0.0",
      "@angular/compiler": "^15.0.0",
      "@angular/compiler-cli": "^15.0.0",
      "@angular/core": "^15.0.0",
      "@angular/platform-browser": "^15.0.0",
      "@angular/platform-browser-dynamic": "^15.0.0"
    },
    "@ngx-file-upload/ui": {
      "@angular/common": "^15.0.0",
      "@angular/compiler": "^15.0.0",
      "@angular/compiler-cli": "^15.0.0",
      "@angular/core": "^15.0.0",
      "@angular/platform-browser": "^15.0.0",
      "@angular/platform-browser-dynamic": "^15.0.0"
    }
  },
```

**Comment by r-hannuschka** [comment]
Updated to angular 15 / 16

For Angular@15 use @ngx-file-upload/core@7
For Angular@16 use @ngx-file-upload/core@8
